### ISSUE TITLE
Modularize failures 

### ISSUE THREAD

**Issue by Shereef** [icarus-sullivan/serverless-plugin-modularize#15]
The below log is me while just added modularize to the npm and serverless.yml without making any further changes

```
Deploying some-service to stage sandbox (us-east-1)

Packaging
AppSync Plugin: GraphQl schema valid
Plugins: ["serverless-plugin-git-variables","serverless-prune-plugin","serverless-appsync-plugin","serverless-plugin-modularize","serverless-newrelic-lambda-layers"]
Adding NewRelic layer to helloWorld
Adding NewRelic layer to healthCheck
Adding NewRelic layer to healthVersion
Excluding development dependencies for service package
Existing New Relic integration found for this linked account and aws account, skipping creation.
Retrieving CloudFormation stack
Uploading
Uploading CloudFormation file to S3
Uploading service some-service.zip file to S3 (1.11 MB)
Updating CloudFormation stack
Creating new change set
Waiting for new change set to be created
Change Set did not reach desired state, retrying
Change Set did not reach desired state, retrying
Change Set did not reach desired state, retrying
Executing created change set
  UPDATE_IN_PROGRESS - AWS::CloudFormation::Stack - some-service-sandbox
  CREATE_IN_PROGRESS - AWS::DynamoDB::Table - DynamoDbTable
  UPDATE_IN_PROGRESS - AWS::Lambda::Function - HealthCheckLambdaFunction
  UPDATE_IN_PROGRESS - AWS::Lambda::Function - HealthVersionLambdaFunction
  UPDATE_IN_PROGRESS - AWS::Lambda::Function - HelloWorldLambdaFunction
  CREATE_IN_PROGRESS - AWS::DynamoDB::Table - DynamoDbTable
  UPDATE_IN_PROGRESS - AWS::AppSync::ApiKey - GraphQlApiKeyappSyncApiKey
  UPDATE_COMPLETE - AWS::AppSync::ApiKey - GraphQlApiKeyappSyncApiKey
  CREATE_COMPLETE - AWS::DynamoDB::Table - DynamoDbTable
  UPDATE_COMPLETE - AWS::Lambda::Function - HealthVersionLambdaFunction
  CREATE_IN_PROGRESS - AWS::Lambda::Version - HealthVersionLambdaVersionH8iXTtuszYMsoaIF2fCwg6I0G3v7OT3t6yba15xgOvc
  CREATE_IN_PROGRESS - AWS::Lambda::Version - HealthVersionLambdaVersionH8iXTtuszYMsoaIF2fCwg6I0G3v7OT3t6yba15xgOvc
  UPDATE_COMPLETE - AWS::Lambda::Function - HelloWorldLambdaFunction
  CREATE_COMPLETE - AWS::Lambda::Version - HealthVersionLambdaVersionH8iXTtuszYMsoaIF2fCwg6I0G3v7OT3t6yba15xgOvc
  CREATE_IN_PROGRESS - AWS::Lambda::Version - HelloWorldLambdaVersionUhwzrYK7ylDwHozvZzCzs6MMWEtKKAkIfFr5b9ug4
  CREATE_IN_PROGRESS - AWS::Lambda::Version - HelloWorldLambdaVersionUhwzrYK7ylDwHozvZzCzs6MMWEtKKAkIfFr5b9ug4
  CREATE_COMPLETE - AWS::Lambda::Version - HelloWorldLambdaVersionUhwzrYK7ylDwHozvZzCzs6MMWEtKKAkIfFr5b9ug4
  UPDATE_COMPLETE - AWS::Lambda::Function - HealthCheckLambdaFunction
  CREATE_IN_PROGRESS - AWS::Lambda::Version - HealthCheckLambdaVersionKDqmucmQS2WYfTX0t27F7SznFFGrbtxc9ucrt4k54
  CREATE_IN_PROGRESS - AWS::Lambda::Version - HealthCheckLambdaVersionKDqmucmQS2WYfTX0t27F7SznFFGrbtxc9ucrt4k54
  CREATE_COMPLETE - AWS::Lambda::Version - HealthCheckLambdaVersionKDqmucmQS2WYfTX0t27F7SznFFGrbtxc9ucrt4k54
  UPDATE_COMPLETE_CLEANUP_IN_PROGRESS - AWS::CloudFormation::Stack - some-service-sandbox
  DELETE_SKIPPED - AWS::Lambda::Version - HealthVersionLambdaVersionZTd07fkZWTaMxoezZpk813Kmcwkb9IlUCaFbCOjqFY
  DELETE_SKIPPED - AWS::Lambda::Version - HelloWorldLambdaVersion76867YHA8GQPNYaNAEbKDPRleIfy9q5GPd8dGsWn8s
  DELETE_SKIPPED - AWS::Lambda::Version - HealthCheckLambdaVersionsvz6QZS0pKBjcQlsl6wxe0W3cjMvqMdH9AcGF4lRZM
  UPDATE_COMPLETE - AWS::CloudFormation::Stack - some-service-sandbox
Retrieving CloudFormation stack
appsync api keys:
  da2-aijrntzqb5ettc5juclixuldpm
appsync endpoints:
  https://mjdmoshdpjfbxpdt57jupqzmqi.appsync-api.us-east-1.amazonaws.com/graphql
Deleting function version some-service-sandbox-helloWorld:42.
Deleting function version some-service-sandbox-healthCheck:12.
Deleting function version some-service-sandbox-healthVersion:12.
✔ Pruning of functions complete
log filter: 
Configuring New Relic log subscription for helloWorld
Configuring New Relic log subscription for healthCheck
Configuring New Relic log subscription for healthVersion
Found log subscription for some-service-sandbox-healthCheck, verifying configuration
Found log subscription for some-service-sandbox-helloWorld, verifying configuration
Found log subscription for some-service-sandbox-healthVersion, verifying configuration
Removing old service artifacts from S3

✔ Service deployed to stack some-service-sandbox (133s)

functions:
  helloWorld: some-service-sandbox-helloWorld (1.1 MB)
  healthCheck: some-service-sandbox-healthCheck (1.1 MB)
  healthVersion: some-service-sandbox-healthVersion (1.1 MB)

Stack Outputs:
  HelloWorldLambdaFunctionQualifiedArn: arn:aws:lambda:us-east-1:*************:function:some-service-sandbox-helloWorld:45
  HealthCheckLambdaFunctionQualifiedArn: arn:aws:lambda:us-east-1:*************:function:some-service-sandbox-healthCheck:15
  GraphQlApiUrl: https://mjdmoshdpjfbxpdt57jupqzmqi.appsync-api.us-east-1.amazonaws.com/graphql
  HealthVersionLambdaFunctionQualifiedArn: arn:aws:lambda:us-east-1:*************:function:some-service-sandbox-healthVersion:15
  GraphQlApiKeyappSyncApiKey: da2-*******************
  GraphQlApiId: ****************************
  ServerlessDeploymentBucketName: some-service-serverlessdeploymentbuck-************
```Deploying some-service to stage sandbox (us-east-1)

Packaging
AppSync Plugin: GraphQl schema valid
Plugins: ["serverless-plugin-git-variables","serverless-prune-plugin","serverless-appsync-plugin","serverless-plugin-modularize","serverless-newrelic-lambda-layers"]
Adding NewRelic layer to helloWorld
Adding NewRelic layer to healthCheck
Adding NewRelic layer to healthVersion
Excluding development dependencies for service package
Existing New Relic integration found for this linked account and aws account, skipping creation.
Retrieving CloudFormation stack
Uploading
Uploading CloudFormation file to S3
Uploading service some-service.zip file to S3 (1.11 MB)
Updating CloudFormation stack
Creating new change set
Waiting for new change set to be created
Change Set did not reach desired state, retrying
Change Set did not reach desired state, retrying
Change Set did not reach desired state, retrying
Executing created change set
  UPDATE_IN_PROGRESS - AWS::CloudFormation::Stack - some-service-sandbox
  CREATE_IN_PROGRESS - AWS::DynamoDB::Table - DynamoDbTable
  UPDATE_IN_PROGRESS - AWS::Lambda::Function - HealthCheckLambdaFunction
  UPDATE_IN_PROGRESS - AWS::Lambda::Function - HealthVersionLambdaFunction
  UPDATE_IN_PROGRESS - AWS::Lambda::Function - HelloWorldLambdaFunction
  CREATE_IN_PROGRESS - AWS::DynamoDB::Table - DynamoDbTable
  UPDATE_IN_PROGRESS - AWS::AppSync::ApiKey - GraphQlApiKeyappSyncApiKey
  UPDATE_COMPLETE - AWS::AppSync::ApiKey - GraphQlApiKeyappSyncApiKey
  CREATE_COMPLETE - AWS::DynamoDB::Table - DynamoDbTable
  UPDATE_COMPLETE - AWS::Lambda::Function - HealthVersionLambdaFunction
  CREATE_IN_PROGRESS - AWS::Lambda::Version - HealthVersionLambdaVersionH8iXTtuszYMsoaIF2fCwg6I0G3v7OT3t6yba15xgOvc
  CREATE_IN_PROGRESS - AWS::Lambda::Version - HealthVersionLambdaVersionH8iXTtuszYMsoaIF2fCwg6I0G3v7OT3t6yba15xgOvc
  UPDATE_COMPLETE - AWS::Lambda::Function - HelloWorldLambdaFunction
  CREATE_COMPLETE - AWS::Lambda::Version - HealthVersionLambdaVersionH8iXTtuszYMsoaIF2fCwg6I0G3v7OT3t6yba15xgOvc
  CREATE_IN_PROGRESS - AWS::Lambda::Version - HelloWorldLambdaVersionUhwzrYK7ylDwHozvZzCzs6MMWEtKKAkIfFr5b9ug4
  CREATE_IN_PROGRESS - AWS::Lambda::Version - HelloWorldLambdaVersionUhwzrYK7ylDwHozvZzCzs6MMWEtKKAkIfFr5b9ug4
  CREATE_COMPLETE - AWS::Lambda::Version - HelloWorldLambdaVersionUhwzrYK7ylDwHozvZzCzs6MMWEtKKAkIfFr5b9ug4
  UPDATE_COMPLETE - AWS::Lambda::Function - HealthCheckLambdaFunction
  CREATE_IN_PROGRESS - AWS::Lambda::Version - HealthCheckLambdaVersionKDqmucmQS2WYfTX0t27F7SznFFGrbtxc9ucrt4k54
  CREATE_IN_PROGRESS - AWS::Lambda::Version - HealthCheckLambdaVersionKDqmucmQS2WYfTX0t27F7SznFFGrbtxc9ucrt4k54
  CREATE_COMPLETE - AWS::Lambda::Version - HealthCheckLambdaVersionKDqmucmQS2WYfTX0t27F7SznFFGrbtxc9ucrt4k54
  UPDATE_COMPLETE_CLEANUP_IN_PROGRESS - AWS::CloudFormation::Stack - some-service-sandbox
  DELETE_SKIPPED - AWS::Lambda::Version - HealthVersionLambdaVersionZTd07fkZWTaMxoezZpk813Kmcwkb9IlUCaFbCOjqFY
  DELETE_SKIPPED - AWS::Lambda::Version - HelloWorldLambdaVersion76867YHA8GQPNYaNAEbKDPRleIfy9q5GPd8dGsWn8s
  DELETE_SKIPPED - AWS::Lambda::Version - HealthCheckLambdaVersionsvz6QZS0pKBjcQlsl6wxe0W3cjMvqMdH9AcGF4lRZM
  UPDATE_COMPLETE - AWS::CloudFormation::Stack - some-service-sandbox
Retrieving CloudFormation stack
appsync api keys:
  da2-aijrntzqb5ettc5juclixuldpm
appsync endpoints:
  https://mjdmoshdpjfbxpdt57jupqzmqi.appsync-api.us-east-1.amazonaws.com/graphql
Deleting function version some-service-sandbox-helloWorld:42.
Deleting function version some-service-sandbox-healthCheck:12.
Deleting function version some-service-sandbox-healthVersion:12.
✔ Pruning of functions complete
log filter: 
Configuring New Relic log subscription for helloWorld
Configuring New Relic log subscription for healthCheck
Configuring New Relic log subscription for healthVersion
Found log subscription for some-service-sandbox-healthCheck, verifying configuration
Found log subscription for some-service-sandbox-helloWorld, verifying configuration
Found log subscription for some-service-sandbox-healthVersion, verifying configuration
Removing old service artifacts from S3

✔ Service deployed to stack some-service-sandbox (133s)

functions:
  helloWorld: some-service-sandbox-helloWorld (1.1 MB)
  healthCheck: some-service-sandbox-healthCheck (1.1 MB)
  healthVersion: some-service-sandbox-healthVersion (1.1 MB)

Stack Outputs:
  HelloWorldLambdaFunctionQualifiedArn: arn:aws:lambda:us-east-1:*************:function:some-service-sandbox-helloWorld:45
  HealthCheckLambdaFunctionQualifiedArn: arn:aws:lambda:us-east-1:*************:function:some-service-sandbox-healthCheck:15
  GraphQlApiUrl: https://mjdmoshdpjfbxpdt57jupqzmqi.appsync-api.us-east-1.amazonaws.com/graphql
  HealthVersionLambdaFunctionQualifiedArn: arn:aws:lambda:us-east-1:*************:function:some-service-sandbox-healthVersion:15
  GraphQlApiKeyappSyncApiKey: da2-****************
  GraphQlApiId: *****************
  ServerlessDeploymentBucketName: some-service-serverlessdeploymentbuck-************
```

Then All I did was move 2 function declarations into `/service/src/health/serverless.module.yml` and removed them from the root serverless.tml

```
functions:
    healthCheck:
        handler: dist/src/health/handler.check
    healthVersion:
        handler: dist/src/health/handler.version
```
This is my glob config:
```
    modularize:
        glob: 'src/**/*.module.yml'
```
The deploy fails with the following output
```
Deploying some-service to stage sandbox (us-east-1)

Packaging
AppSync Plugin: GraphQl schema valid
Plugins: ["serverless-plugin-modularize","serverless-plugin-git-variables","serverless-prune-plugin","serverless-appsync-plugin","serverless-newrelic-lambda-layers"]
Adding NewRelic layer to helloWorld
Excluding development dependencies for service package
Existing New Relic integration found for this linked account and aws account, skipping creation.
Retrieving CloudFormation stack
Uploading
Uploading CloudFormation file to S3
Uploading service some-service.zip file to S3 (1.11 MB)

✖ Stack some-service-sandbox failed to deploy (10s)
Environment: darwin, node 14.18.2, framework 3.0.0 (local), plugin 6.0.0, SDK 4.3.0
Credentials: Local, "sandbox" profile
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

Error:
The CloudFormation template is invalid: Template error: instance of Fn::GetAtt references undefined resource HealthVersionLambdaFunction
```

What info do you need ?
I think it's caused by the new relic plugin `serverless-newrelic-lambda-layers` somehow not being compatible with modularize

**Comment by Shereef** [comment]
`serverless modularize info`

```
Environment: darwin, node 14.18.2, framework 3.0.0 (local), plugin 6.0.0, SDK 4.3.0
Credentials: Local, "default" profile
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

Error:
Cannot resolve serverless.yml: Variables resolution errored with:
  - Cannot resolve variable at "custom.newRelicUserKey": An error occurred while calling one AWS dependency service.
```


`serverless.yml`

```
custom:
    newRelicUserKey: ${ssm:/aws/reference/secretsmanager/NewRelicAPIKey}
    newRelic:
        accountId: 123456789
        cloudWatchFilter: '*'
        apiKey: ${self:custom.newRelicUserKey.NEW_RELIC_USER_KEY}
        linkedAccount: 'someAccount'
```

**Comment by Shereef** [comment]
When I comment out the new relic stuff then also remove the helloWorld function from the main serverless.yml which means the only functions now are in the health module

```
npx serverless modularize info
modularize: src/health/serverless.module.yml 
 {
  "functions": {
    "healthCheck": {
      "handler": "dist/src/health/handler.check"
    },
    "healthVersion": {
      "handler": "dist/src/health/handler.version"
    }
  }
} 

✖ Uncaught exception
/Users/shereef.marzouk/Dev/some/service/node_modules/serverless/scripts/serverless.js:46
        throw error;
        ^

ServerlessError: Function "healthVersion" doesn't exist in this Service
    at Service.getFunction (/Users/shereef.marzouk/Dev/some/service/node_modules/serverless/lib/classes/service.js:314:11)
    at ServerlessGitVariables.exportGitVariables (/Users/shereef.marzouk/Dev/some/service/node_modules/serverless-plugin-git-variables/lib/index.js:198:44) {
  code: 'FUNCTION_MISSING_IN_SERVICE',
  decoratedMessage: undefined
}
```

if I comment out either of the remaining functions it works fine.

I don't understand! Surely modularize can support more than 1 function in a module/lambda

What am I doing wrong ?

**Comment by icarus-sullivan** [comment]
The modularize plugin can handle as many functions per module as you want to add (assuming whatever cloud platform you use accepts it). Have you tried adding the modularize plugin as the first plugin on the list so it is ran before the others?

**Comment by Shereef** [comment]
Thanks for your response
I tried that first thing but it errored out 
I can't remember the error but I'll post that tomorrow

**Comment by icarus-sullivan** [comment]
@Shereef Sounds good, let me know.

**Comment by icarus-sullivan** [comment]
I also noticed you had some files in the dist/src/... etc. If the root level serverless.yml has the global pattern `src/...` it won't look in the dist directory.

**Comment by Shereef** [comment]
That was one of the things I tried as well
I will update you tomorrow thnx

**Comment by Shereef** [comment]
The dist folder is for JS files the repo has the yml in src not in dist
![image](https://user-images.githubusercontent.com/356763/152265505-4f3f6c71-a174-49a9-be3f-ded2dfb16ceb.png)

**Comment by Shereef** [comment]
The kids are asleep I thought I would give you the responses today since you are active now

```
plugins:
    - serverless-plugin-modularize
    - serverless-plugin-git-variables
    - serverless-prune-plugin
    - serverless-appsync-plugin
    - serverless-newrelic-lambda-layers
```

```
Packaging
AppSync Plugin: GraphQl schema valid
Plugins: ["serverless-plugin-modularize","serverless-plugin-git-variables","serverless-prune-plugin","serverless-appsync-plugin","serverless-newrelic-lambda-layers"]
Please use a valid New Relic API key as your apiKey value; skipping.
✖ Uncaught exception
Environment: darwin, node 14.18.2, framework 3.0.0 (local), plugin 6.0.0, SDK 4.3.0
Credentials: Local, "sandbox" profile
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

Error:
Function "healthVersion" doesn't exist in this Service
No New Relic AWS Lambda integration found for this New Relic linked account and aws account.
Please enable the configuration manually or add the 'enableIntegration' config var to your serverless.yaml file.
Retrieving CloudFormation stack
```

**Comment by Shereef** [comment]
When I played around with the order of plugins and commented new relic out

```
Deploying some-service to stage sandbox (us-east-1)

Packaging
AppSync Plugin: GraphQl schema valid
Plugins: ["serverless-plugin-git-variables","serverless-prune-plugin","serverless-appsync-plugin","serverless-newrelic-lambda-layers","serverless-plugin-modularize"]
Please use a valid New Relic API key as your apiKey value; skipping.
No New Relic AWS Lambda integration found for this New Relic linked account and aws account.
Please enable the configuration manually or add the 'enableIntegration' config var to your serverless.yaml file.
Retrieving CloudFormation stack
Uploading
Uploading CloudFormation file to S3

✖ Stack daysmart-booking-service-sandbox failed to deploy (2s)
Environment: darwin, node 14.18.2, framework 3.0.0 (local), plugin 6.0.0, SDK 4.3.0
Credentials: Local, "sandbox" profile
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

Error:
The CloudFormation template is invalid: Template error: instance of Fn::GetAtt references undefined resource HealthVersionLambdaFunction
```

**Comment by Shereef** [comment]
I have created [this repo](https://github.com/Shereef/modularize-issue/commits/master) where I have replicated the issue


I hope this is helpful

P.S.  Each commit that has a comment icon is for you to look at

**Comment by Shereef** [comment]
@icarus-sullivan Any help would be appreciated

**Comment by icarus-sullivan** [comment]
@Shereef I tested locally, I was able to reproduce the issue. I'm wondering if its a conflict with serverless 3.0 since this was targeting 2 when it was published.

**Comment by Shereef** [comment]
I tried downgrading to serverless 2 and pushed my try to the repo above. `  The CloudFormation template is invalid: Template error: instance of Fn::GetAtt references undefined resource HealthVersionLambdaFunction`

Thanks so much for trying it locally. is there anything you think I can try ?

**Comment by icarus-sullivan** [comment]
@Shereef I just released a v2.0.0, which uses serverless internal merging for service-level additions. If you have time please give it a try and let me know if it resolved issues for you.

**Comment by Shereef** [comment]
@icarus-sullivan: I can't get it to work I created this branch https://github.com/Shereef/modularize-issue/commits/simple-sls3-slspmod2 to try it and the modularize merged shows functions correctly but when you deploy it doesn't have functions at all

```
Shmac:modularize-issue shereef.marzouk$ npm run deploy

> some-booking-service@0.0.1 deploy
> npm run build && sls deploy --stage sandbox --aws-profile sandbox --verbose


> some-booking-service@0.0.1 build
> tsc --build --verbose --pretty

[4:32:34 AM] Projects in this build: 
    * tsconfig.json

[4:32:34 AM] Project 'tsconfig.json' is up to date because newest input 'src/shared/functions.ts' is older than oldest output 'dist/src/shared/functions.js'


Deploying some-booking-service to stage sandbox (us-east-1)

Packaging
Retrieving CloudFormation stack
Creating CloudFormation stack
Creating new change set
Waiting for new change set to be created
Change Set did not reach desired state, retrying
Executing created change set
  CREATE_IN_PROGRESS - AWS::CloudFormation::Stack - some-booking-service-sandbox
  CREATE_IN_PROGRESS - AWS::S3::Bucket - ServerlessDeploymentBucket
  CREATE_IN_PROGRESS - AWS::S3::Bucket - ServerlessDeploymentBucket
  CREATE_COMPLETE - AWS::S3::Bucket - ServerlessDeploymentBucket
  CREATE_IN_PROGRESS - AWS::S3::BucketPolicy - ServerlessDeploymentBucketPolicy
  CREATE_IN_PROGRESS - AWS::S3::BucketPolicy - ServerlessDeploymentBucketPolicy
  CREATE_COMPLETE - AWS::S3::BucketPolicy - ServerlessDeploymentBucketPolicy
  CREATE_COMPLETE - AWS::CloudFormation::Stack - some-booking-service-sandbox
Uploading
Uploading CloudFormation file to S3
Updating CloudFormation stack
Creating new change set
Waiting for new change set to be created
Change Set did not reach desired state, retrying
Change Set did not reach desired state, retrying
Executing created change set
  UPDATE_IN_PROGRESS - AWS::CloudFormation::Stack - some-booking-service-sandbox
  UPDATE_COMPLETE_CLEANUP_IN_PROGRESS - AWS::CloudFormation::Stack - some-booking-service-sandbox
  UPDATE_COMPLETE - AWS::CloudFormation::Stack - some-booking-service-sandbox
Retrieving CloudFormation stack
Removing old service artifacts from S3

✔ Service deployed to stack some-booking-service-sandbox (67s)


Stack Outputs:
  ServerlessDeploymentBucketName: some-booking-service-san-serverlessdeploymentbuck-16kzaq4d88sbb
```
```
Shmac:modularize-issue shereef.marzouk$ npx serverless modularize info
modularize: src/health/serverless.module.yml 
 {
  "functions": {
    "healthCheck": {
      "handler": "dist/src/health/handler.check"
    },
    "healthVersion": {
      "handler": "dist/src/health/handler.version"
    }
  }
} 

Shmac:modularize-issue shereef.marzouk$ npx serverless modularize merged
modularize: {
  "plugins": [
    "serverless-plugin-modularize"
  ],
  "custom": {
    "modularize": {
      "glob": "src/**/*.module.yml"
    }
  },
  "provider": {
    "name": "aws",
    "runtime": "nodejs14.x",
    "memorySize": 128,
    "timeout": 120,
    "region": "us-east-1",
    "stage": "dev",
    "versionFunctions": true
  },
  "functions": {
    "healthCheck": {
      "handler": "dist/src/health/handler.check"
    },
    "healthVersion": {
      "handler": "dist/src/health/handler.version"
    }
  }
}
Shmac:modularize-issue shereef.marzouk$ 
```

**Comment by Shereef** [comment]
I think we will need to work with @serverless to fix this.

it works fine if I have 1 function in the `serverless.yml`

so I think it's the serverless code that's not deploying the functions even though they exist in the runtime config after `service.update`.

**Comment by Shereef** [comment]
I created #16 we can close this one

Thanks so much!

**Comment by icarus-sullivan** [comment]
Yeah, I bet they check if there are any functions in the main file and ignore any subsequent checks for those files.

**Comment by Shereef** [comment]
Thanks so much for releasing 2.0.0. I have it working in my main repo now and the `serverless.yml` is so much smaller now!

**Comment by icarus-sullivan** [comment]
Was it serverless@2.72.2 that got it to work?

**Comment by Shereef** [comment]
The latest serverless@3.2.0

2.72.2 wasn't even getting the functions in the merged command
